# Generated by Django 5.0 on 2026-01-07 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0002_alter_comment_options_comment_parent_post_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="social_app__post_id_4d78e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="social_app__user_id_490b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="social_app__parent__1d8001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(fields=["name"], name="social_app__name_9ed407_idx"),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["created_at"], name="social_app__created_314486_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "post"], name="social_app__user_id_808141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "created_at"], name="social_app__post_id_e75892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="social_app__recipie_f78ac2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="social_app__recipie_938439_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sender", "-created_at"], name="social_app__sender__4866f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="social_app__notific_d914d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="social_app__created_197595_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "-created_at"], name="social_app__user_id_4a7357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_pinned", "-created_at"],
                name="social_app__is_pinn_48651f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_verified"], name="social_app__is_veri_f9dc69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["created_at"], name="social_app__created_f0a5d5_idx"
            ),
        ),
    ]
