# Generated by Django 5.0 on 2026-01-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0003_add_database_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/videos/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
    ]
